# CircleCI config for automated test builds triggered from Github.
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: apt update && apt install -y python g++ postgresql libpq-dev make autoconf dh-autoreconf autoconf-archive automake
      - run:
          name: Set up database
          command: mkdir db && PGDATA=db/data initdb && PGHOST=$(pwd)/db createdb $(whoami)
      - run:
          name: Start database
          run: PGDATA=db/data postgres -- -F -h '' -k db &
      - run:
          name: Configure
          command: CXXFLAGS=-O0 CONFIG_ARGS=--disable-documentation ./autogen.sh
      - run:
          name: Make
          command: make
      - run:
          name: Test
          command: PGDATA=db/data make check
