# CircleCI config for automated test builds triggered from Github.
version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install
          command: sudo apt update && sudo apt upgrade && sudo apt install g++
      - run:
          name: Configure
          command: ./configure CXXFLAGS=-O0 --enable-maintainer-mode --disable-documentation
      - run:
          name: Make
          command: make
      - run:
          name: Test
          command: make check
