# CircleCI config for automated test builds triggered from Github.
version: 2
jobs:
  build:
    docker:
      - image: postgres:latest
    steps:
      - checkout
      - run:
          name: Install
          command: apt update && apt install -y python g++ libpq-dev postgresql build-essential make autoconf dh-autoreconf autoconf-archive automake
      - run: 
          name: Set up database
          command: |
              dockerize -wait tcp://localhost:5432 -timeout 1m &&
              ps -ef &&
              su postgres -p -c "createuser -h localhost -d $(whoami)" &&
              createdb -h localhost $(whoami)
      - run:
          name: Configure
          command: CXXFLAGS=-O0 CONFIG_ARGS=--disable-documentation ./autogen.sh
      - run:
          name: Make
          command: make
      - run:
          name: Test
          command: PGDATA=db/data make check
